name: Build and Test

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-14

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build and Test
        run: |
          ls /Applications | grep Xcode
          sudo xcode-select --switch /Applications/Xcode_15.3.app/Contents/Developer
            
          # Build the project and run the tests
          xcodebuild \
            -project TypeReader.xcodeproj \
            -scheme TypeReader \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.4' \
            clean test | xcbeautify --quiet --is-ci --renderer github-actions

        continue-on-error: false

