name: CI for Xcode Project

on:
  # This workflow runs on every push and pull request to the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-14

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build and Test
        run: |
          ls /Applications | grep Xcode
          sudo xcode-select --switch /Applications/Xcode_15.3.app/Contents/Developer
            
          # Build the project and run the tests
          xcodebuild \
            -project TypeReader.xcodeproj \
            -scheme TypeReader \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.4' \
            clean test | xcbeautify

        # This will fail the job if any test fails
        continue-on-error: false

